### ISSUE TITLE
The FAQ hides the detail arrows

### ISSUE THREAD

**Issue by chocolateboy** [violentmonkey/violentmonkey.github.io#1]
| software         | version(s)
| ---------------- | -------
| Browser        | Firefox 58.0.2, Waterfox 56.0.4.1
| Operating System | Linux (Arch)

This addon looks awesome, but I got the wrong impression from the FAQ:

## Actual

<a href="https://i.imgur.com/lq4DAco.png" title="Visible"><img src="https://i.imgur.com/lq4DAco.png" alt="Visible"/></a>

## Expected

<a href="https://i.imgur.com/IxR5TjS.png" title="Hidden"><img src="https://i.imgur.com/IxR5TjS.png" alt="Hidden"/></a>

I only noticed the detail for the clipboard FAQ because I accidentally clicked it. And I've only just noticed, while writing this up and figuring out what rule is hiding the arrows, that there's also an important detail for the sync FAQ...

This is the [offending rule](https://github.com/violentmonkey/violentmonkey.github.io/blob/23609b3fe491074f9e496b3881bb0df564461b4a/css/style.css#L20-L21):

```css
summary {
    display: block;
}
```

(I assume that the hidden arrows are accidental, since they're displayed correctly in a Chromium derivative, but I'm wondering if it's a good idea to hide the details at all, given that they address serious privacy concerns. I was going to write the addon off as dangerous (at best) until I read the detailed explanation for the `GM_setClipboard` permission (which I wasn't aware of in Greasemonkey).)

**Comment by gera2ld** [comment]
Thanks for reminding. 👍
