### ISSUE TITLE
Make source of the website private

### ISSUE THREAD

**Issue by gera2ld** [violentmonkey/violentmonkey.github.io#16]
I am thinking about making the source code of this website private, because I found someone copied Violentmonkey, changed its name, added ads, and released as a new add-on. What's more, they copied the whole website and did the same with it.

Violentmonkey has a license of MIT, so it's OK to be modified and republished. But the website is not.

References:
- https://github.com/acestream/webextension/issues/1
- https://chrome.google.com/webstore/detail/ace-script/mjbepbhonbojpoaenhckjocchgfiaofo
- http://acescript.acestream.me/

**Comment by tophf** [comment]
MIT license [doesn't allow to copy or modify without attribution](https://tldrlegal.com/license/mit-license) so that other extension violates the license.

**Comment by tophf** [comment]
Hmm, they include it in their github repo though.

**Comment by MarkookSMH** [comment]
Hello, one of the reviewer of that extension warns that someone has tried to access to his steam account after installing that extension. If this is the case, you guys simply should report the extension to chrome to remove it.

Anyways, look at this extension: https://chrome.google.com/webstore/detail/moraviamonkey-beta/fgdojojlaebffcecoenkneflmacbkone

**Comment by gera2ld** [comment]
@MarkookSMH That is not our extension and never linked to in this website. So I guess we don't have much to do here.
