### ISSUE TITLE
Show contents of "Get It" in the main page

### ISSUE THREAD

**Issue by tophf** [violentmonkey/violentmonkey.github.io#37]
The main page has confused me every time I opened it, scrolled down, and clicked the browser icon to download the extension. Instead it just opened the png file.

I think a good solution would be to show the Get it page instead of "Supported Browsers" block.
I tried doing it with gatsby-remark-embed-markdown, but failed.
Maybe there's a better method, I just don't know.

As for the image links, the simplest workaround would be to use html:
```html
- <img src="../src/assets/alternatives/greasemonkey.png"/> Greasemonkey
- <img src="../src/assets/alternatives/tampermonkey.png"/> Tampermonkey
```

**Comment by gera2ld** [comment]
> I think a good solution would be to show the Get it page instead of "Supported Browsers" block.

Hm in that case we remove the Get-it page and everything will be in the main page, right?

I think the alternatives part can be removed haha.
