### ISSUE TITLE
The "Guide" and "API" links at the top don't work

### ISSUE THREAD

**Issue by buenoudg** [violentmonkey/violentmonkey.github.io#42]
- "Guide" points to https://violentmonkey.github.io/guide/ instead of https://violentmonkey.github.io/guide/creating-a-userscript/ (which is where the guide apparently starts)
- "API" points to https://violentmonkey.github.io/api/ instead of https://violentmonkey.github.io/api/gm/ (which is where the API documentation apparently starts)
- https://violentmonkey.github.io/guide/ and https://violentmonkey.github.io/api/ both return an HTTP 404

**Comment by tophf** [comment]
Although all links work for me and redirect to the target pages, I guess they should be fixed to point to the real URLs anyway.

**Comment by buenoudg** [comment]
Oh. You're right. I hadn't enabled JavaScript for the violentmonkey.github.io domain (duh). I should have suspected that such a "bug" would have been noticed immediately 😁
