### ISSUE TITLE
The definition of `document-end` is incorrect

### ISSUE THREAD

**Issue by gera2ld** [violentmonkey/violentmonkey.github.io#43]
The definition of `document-end` in our docs is incorrect as we switched from `DOMContentLoaded` to `document-end` of [extensionTypes.RunAt](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extensionTypes/RunAt).

According to MDN, `document-end` now means `document.readyState = 'interactive'`, aka. the document finishes parsing but  resources like `<script defer>` might still be loading. However, `DOMContentLoaded` only happens after `<script defer>` are loaded.

**Comment by tophf** [comment]
> [defer](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer) is set to indicate to a browser that the script is meant to be executed after the document has been parsed, but **before firing DOMContentLoaded**.

Which means our definition is correct.

**Comment by tophf** [comment]
Ah, you mean our behavior is correct but the docs are not.

**Comment by gera2ld** [comment]
It seems I was wrong, we didn't switch to `document-end` of `extensionTypes.RunAt`. I must have something wrong in my scripts, sorry for the spam.
